### ISSUE TITLE
Container CSS customization

### ISSUE THREAD

**Issue by drev74** [PNKBizz/vue-yandex-maps#33]
Hello I'd like to have a rounded borders for my map. I'm trying to do this:
```css
.yandex-container {
  height: 200px;
  width: 200px;
  border-radius: 200px;
}
```
`Border-radius` doesn't work. I found no CSS examples in the Yandex Maps official [sandbox](https://yandex.ru/dev/maps/jsbox/2.1/).
Is there a possibility to change container settings? I tried `tailwind` and it also fails to apply classes to the maps component.

```vue
// tailwind class is not applied to the yandex container
<div class="rounded-3xl">
  <Map >/
</div>
